name: PVEToggleV2
version: 2.0
main: com.ixeriox.PVEToggleV2
author: iXeriox
api-version: 1.13
description: A plugin to toggle PVE in Minecraft.
commands:
  pve:
    description: PVE control
    usage: /pve (Toggle/status)
