name: PVEToggle
version: 1.0.0
api-version: 1.13
main: com.ixeriox.PVEToggle.PVEToggle
author: iXeriox
description: PVEToggle requested by LadyHaley(Spigot)

commands:
  pve:
    description: controls the whole PVE-Toggle command base. Including Toggle/reload and admin!